insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Absorb', 'Grass', '', 20, 100, '1');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Acid', 'Poison', '', 40, 100, '2');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Acid Armor', 'Poison', '', NULL, NULL, '3');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Agility', 'Psychic', '', NULL, NULL, '4');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Amnesia', 'Psychic', '', NULL, NULL, '5');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Aurora Beam', 'Ice', '', 65, 100, '6');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Barrage', 'Normal', '', 15, 85, '7');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Barrier', 'Psychic', '', NULL, NULL, '8');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Bide', 'Normal', '', NULL, NULL, '9');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Bind', 'Normal', '', 15, 85, '10');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Bite', 'Dark', '', 60, 100, '11');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Blizzard', 'Ice', '', 110, 70, '12');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Body Slam', 'Normal', '', 85, 100, '13');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Bone Club', 'Ground', '', 65, 85, '14');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Bonemerang', 'Ground', '', 50, 90, '15');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Bubble', 'Water', '', 40, 100, '16');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Bubble Beam', 'Water', '', 65, 100, '17');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Clamp', 'Water', '', 35, 85, '18');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Comet Punch', 'Normal', '', 18, 85, '19');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Confuse Ray', 'Ghost', '', NULL, 100, '20');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Confusion', 'Psychic', '', 50, 100, '21');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Constrict', 'Normal', '', 10, 100, '22');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Conversion', 'Normal', '', NULL, NULL, '23');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Counter', 'Fighting', '', NULL, 100, '24');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Crabhammer', 'Water', '', 100, 90, '25');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Cut', 'Normal', '', 50, 95, '26');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Defense Curl', 'Normal', '', NULL, NULL, '27');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Dig', 'Ground', '', 80, 100, '28');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Disable', 'Normal', '', NULL, 100, '29');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Dizzy Punch', 'Normal', '', 70, 100, '30');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Double Kick', 'Fighting', '', 30, 100, '31');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Double Slap', 'Normal', '', 15, 85, '32');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Double Team', 'Normal', '', NULL, NULL, '33');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Double-Edge', 'Normal', '', 120, 100, '34');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Dragon Rage', 'Dragon', '', NULL, 100, '35');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Dream Eater', 'Psychic', '', 100, 100, '36');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Drill Peck', 'Flying', '', 80, 100, '37');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Earthquake', 'Ground', '', 100, 100, '38');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Egg Bomb', 'Normal', '', 100, 75, '39');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Ember', 'Fire', '', 40, 100, '40');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Explosion', 'Normal', '', 250, 100, '41');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Fire Blast', 'Fire', '', 110, 85, '42');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Fire Punch', 'Fire', '', 75, 100, '43');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Fire Spin', 'Fire', '', 35, 85, '44');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Fissure', 'Ground', '', NULL, 30, '45');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Flamethrower', 'Fire', '', 90, 100, '46');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Flash', 'Normal', '', NULL, 100, '47');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Fly', 'Flying', '', 90, 95, '48');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Focus Energy', 'Normal', '', NULL, NULL, '49');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Fury Attack', 'Normal', '', 15, 85, '50');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Fury Swipes', 'Normal', '', 18, 80, '51');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Glare', 'Normal', '', NULL, 100, '52');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Growl', 'Normal', '', NULL, 100, '53');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Growth', 'Normal', '', NULL, NULL, '54');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Guillotine', 'Normal', '', NULL, 30, '55');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Gust', 'Flying', '', 40, 100, '56');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Harden', 'Normal', '', NULL, NULL, '57');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Haze', 'Ice', '', NULL, NULL, '58');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Headbutt', 'Normal', '', 70, 100, '59');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('High Jump Kick', 'Fighting', '', 130, 90, '60');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Horn Attack', 'Normal', '', 65, 100, '61');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Horn Drill', 'Normal', '', NULL, 30, '62');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Hydro Pump', 'Water', '', 110, 80, '63');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Hyper Beam', 'Normal', '', 150, 90, '64');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Hyper Fang', 'Normal', '', 80, 90, '65');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Hypnosis', 'Psychic', '', NULL, 60, '66');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Ice Beam', 'Ice', '', 90, 100, '67');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Ice Punch', 'Ice', '', 75, 100, '68');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Jump Kick', 'Fighting', '', 100, 95, '69');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Karate Chop', 'Fighting', '', 50, 100, '70');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Kinesis', 'Psychic', '', NULL, 80, '71');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Leech Life', 'Bug', '', 80, 100, '72');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Leech Seed', 'Grass', '', NULL, 90, '73');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Leer', 'Normal', '', NULL, 100, '74');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Lick', 'Ghost', '', 30, 100, '75');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Light Screen', 'Psychic', '', NULL, NULL, '76');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Lovely Kiss', 'Normal', '', NULL, 75, '77');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Low Kick', 'Fighting', '', NULL, 100, '78');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Meditate', 'Psychic', '', NULL, NULL, '79');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Mega Drain', 'Grass', '', 40, 100, '80');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Mega Kick', 'Normal', '', 120, 75, '81');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Mega Punch', 'Normal', '', 80, 85, '82');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Metronome', 'Normal', '', NULL, NULL, '83');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Mimic', 'Normal', '', NULL, NULL, '84');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Minimize', 'Normal', '', NULL, NULL, '85');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Mirror Move', 'Flying', '', NULL, NULL, '86');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Mist', 'Ice', '', NULL, NULL, '87');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Night Shade', 'Ghost', '', NULL, 100, '88');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Pay Day', 'Normal', '', 40, 100, '89');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Peck', 'Flying', '', 35, 100, '90');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Petal Dance', 'Grass', '', 120, 100, '91');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Pin Missile', 'Bug', '', 25, 95, '92');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Poison Gas', 'Poison', '', NULL, 90, '93');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Poison Powder', 'Poison', '', NULL, 75, '94');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Poison Sting', 'Poison', '', 15, 100, '95');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Pound', 'Normal', '', 40, 100, '96');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Psybeam', 'Psychic', '', 65, 100, '97');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Psychic', 'Psychic', '', 90, 100, '98');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Psywave', 'Psychic', '', NULL, 100, '99');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Quick Attack', 'Normal', '', 40, 100, '100');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Rage', 'Normal', '', 20, 100, '101');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Razor Leaf', 'Grass', '', 55, 95, '102');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Razor Wind', 'Normal', '', 80, 100, '103');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Recover', 'Normal', '', NULL, NULL, '104');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Reflect', 'Psychic', '', NULL, NULL, '105');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Rest', 'Psychic', '', NULL, NULL, '106');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Roar', 'Normal', '', NULL, NULL, '107');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Rock Slide', 'Rock', '', 75, 90, '108');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Rock Throw', 'Rock', '', 50, 90, '109');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Rolling Kick', 'Fighting', '', 60, 85, '110');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Sand Attack', 'Ground', '', NULL, 100, '111');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Scratch', 'Normal', '', 40, 100, '112');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Screech', 'Normal', '', NULL, 85, '113');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Seismic Toss', 'Fighting', '', NULL, 100, '114');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Self-Destruct', 'Normal', '', 200, 100, '115');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Sharpen', 'Normal', '', NULL, NULL, '116');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Sing', 'Normal', '', NULL, 55, '117');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Skull Bash', 'Normal', '', 130, 100, '118');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Sky Attack', 'Flying', '', 140, 90, '119');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Slam', 'Normal', '', 80, 75, '120');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Slash', 'Normal', '', 70, 100, '121');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Sleep Powder', 'Grass', '', NULL, 75, '122');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Sludge', 'Poison', '', 65, 100, '123');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Smog', 'Poison', '', 30, 70, '124');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Smokescreen', 'Normal', '', NULL, 100, '125');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Soft-Boiled', 'Normal', '', NULL, NULL, '126');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Solar Beam', 'Grass', '', 120, 100, '127');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Sonic Boom', 'Normal', '', NULL, 90, '128');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Spike Cannon', 'Normal', '', 20, 100, '129');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Splash', 'Normal', '', NULL, NULL, '130');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Spore', 'Grass', '', NULL, 100, '131');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Stomp', 'Normal', '', 65, 100, '132');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Strength', 'Normal', '', 80, 100, '133');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('String Shot', 'Bug', '', NULL, 95, '134');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Struggle', 'Normal', '', 50, NULL, '135');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Stun Spore', 'Grass', '', NULL, 75, '136');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Submission', 'Fighting', '', 80, 80, '137');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Substitute', 'Normal', '', NULL, NULL, '138');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Super Fang', 'Normal', '', NULL, 90, '139');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Supersonic', 'Normal', '', NULL, 55, '140');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Surf', 'Water', '', 90, 100, '141');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Swift', 'Normal', '', 60, ∞, '142');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Swords Dance', 'Normal', '', NULL, NULL, '143');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Tackle', 'Normal', '', 40, 100, '144');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Tail Whip', 'Normal', '', NULL, 100, '145');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Take Down', 'Normal', '', 90, 85, '146');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Teleport', 'Psychic', '', NULL, NULL, '147');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Thrash', 'Normal', '', 120, 100, '148');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Thunder', 'Electric', '', 110, 70, '149');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Thunder Punch', 'Electric', '', 75, 100, '150');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Thunder Shock', 'Electric', '', 40, 100, '151');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Thunder Wave', 'Electric', '', NULL, 90, '152');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Thunderbolt', 'Electric', '', 90, 100, '153');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Toxic', 'Poison', '', NULL, 90, '154');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Transform', 'Normal', '', NULL, NULL, '155');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Tri Attack', 'Normal', '', 80, 100, '156');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Twineedle', 'Bug', '', 25, 100, '157');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Vine Whip', 'Grass', '', 45, 100, '158');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Vise Grip', 'Normal', '', 55, 100, '159');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Water Gun', 'Water', '', 40, 100, '160');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Waterfall', 'Water', '', 80, 100, '161');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Whirlwind', 'Normal', '', NULL, NULL, '162');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Wing Attack', 'Flying', '', 60, 100, '163');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Withdraw', 'Water', '', NULL, NULL, '164');
insert into Move (AttackName, MoveType, DamageCategory, MovePower, Accuracy, PokemonName) values ('Wrap', 'Normal', '', 15, 90, '165');
