insert into Team (TeamName, TrainerName, PokemonName) values ('lmccomiskey0', 'Lewie', 'Black swan');
insert into Team (TeamName, TrainerName, PokemonName) values ('gpigeon1', 'Georgetta', 'Red-legged pademelon');
insert into Team (TeamName, TrainerName, PokemonName) values ('estruijs2', 'Esma', 'Squirrel, grey-footed');
insert into Team (TeamName, TrainerName, PokemonName) values ('oquemby3', 'Olly', 'Darwin ground finch (unidentified)');
insert into Team (TeamName, TrainerName, PokemonName) values ('jgulvin4', 'Justinian', 'Pig-tailed macaque');
insert into Team (TeamName, TrainerName, PokemonName) values ('sstout5', 'Salomone', 'Miner''s cat');
insert into Team (TeamName, TrainerName, PokemonName) values ('eoxford6', 'Englebert', 'Greater rhea');
insert into Team (TeamName, TrainerName, PokemonName) values ('rjentgens7', 'Ric', 'Two-toed sloth');
insert into Team (TeamName, TrainerName, PokemonName) values ('mbenardette8', 'Manny', 'Black-footed ferret');
insert into Team (TeamName, TrainerName, PokemonName) values ('ibaggarley9', 'Ilene', 'Sage grouse');
insert into Team (TeamName, TrainerName, PokemonName) values ('rbrutya', 'Raddie', 'Weaver, lesser masked');
insert into Team (TeamName, TrainerName, PokemonName) values ('sfleyb', 'Stanford', 'Nighthawk, common');
insert into Team (TeamName, TrainerName, PokemonName) values ('tferenczc', 'Thain', 'White-browed sparrow weaver');
insert into Team (TeamName, TrainerName, PokemonName) values ('gbrownscombed', 'Gustavo', 'Bonnet macaque');
insert into Team (TeamName, TrainerName, PokemonName) values ('tbriskeye', 'Tonya', 'Lizard, mexican beaded');
insert into Team (TeamName, TrainerName, PokemonName) values ('sglynnef', 'Shell', 'Indian giant squirrel');
insert into Team (TeamName, TrainerName, PokemonName) values ('shurryg', 'Sawyere', 'Lemur, brown');
insert into Team (TeamName, TrainerName, PokemonName) values ('gyoleh', 'Georges', 'African buffalo');
insert into Team (TeamName, TrainerName, PokemonName) values ('rsineathi', 'Revkah', 'Phascogale, brush-tailed');
insert into Team (TeamName, TrainerName, PokemonName) values ('pwinmillj', 'Peg', 'Egyptian vulture');
insert into Team (TeamName, TrainerName, PokemonName) values ('ayurshevk', 'Adelheid', 'Blue racer');
insert into Team (TeamName, TrainerName, PokemonName) values ('pcassonl', 'Paolina', 'Long-crested hawk eagle');
insert into Team (TeamName, TrainerName, PokemonName) values ('kmargremm', 'Kerry', 'Asiatic wild ass');
insert into Team (TeamName, TrainerName, PokemonName) values ('kgrinnikovn', 'Karl', 'Wolf, timber');
insert into Team (TeamName, TrainerName, PokemonName) values ('sstubbingso', 'Stephi', 'Raven, white-necked');
insert into Team (TeamName, TrainerName, PokemonName) values ('amctiernanp', 'Abigale', 'Mallard');
insert into Team (TeamName, TrainerName, PokemonName) values ('pharrowerq', 'Prentice', 'Collared lemming');
insert into Team (TeamName, TrainerName, PokemonName) values ('jdudmarshr', 'Joellen', 'Lemur, ring-tailed');
insert into Team (TeamName, TrainerName, PokemonName) values ('bferriss', 'Brittni', 'Nine-banded armadillo');
insert into Team (TeamName, TrainerName, PokemonName) values ('edehooght', 'Erena', 'Pheasant, ring-necked');
insert into Team (TeamName, TrainerName, PokemonName) values ('gcluleyu', 'Gustavo', 'Tern, white-winged');
insert into Team (TeamName, TrainerName, PokemonName) values ('sduplainv', 'Sibeal', 'Greater roadrunner');
insert into Team (TeamName, TrainerName, PokemonName) values ('esauvanw', 'Englebert', 'Banded mongoose');
insert into Team (TeamName, TrainerName, PokemonName) values ('thusthwaitex', 'Thalia', 'Baboon, savanna');
insert into Team (TeamName, TrainerName, PokemonName) values ('rengehamy', 'Ryon', 'Crab, sally lightfoot');
insert into Team (TeamName, TrainerName, PokemonName) values ('aknokz', 'Andie', 'Legaan, ground');
insert into Team (TeamName, TrainerName, PokemonName) values ('greavell10', 'Gloria', 'Brown lemur');
insert into Team (TeamName, TrainerName, PokemonName) values ('cneads11', 'Clayborne', 'Fox, grey');
insert into Team (TeamName, TrainerName, PokemonName) values ('jhainey12', 'Julianne', 'Bat-eared fox');
insert into Team (TeamName, TrainerName, PokemonName) values ('pfrays13', 'Padriac', 'Long-tailed spotted cat');
insert into Team (TeamName, TrainerName, PokemonName) values ('ltabbernor14', 'Leda', 'Peregrine falcon');
insert into Team (TeamName, TrainerName, PokemonName) values ('volagene15', 'Valerie', 'Cape Barren goose');
insert into Team (TeamName, TrainerName, PokemonName) values ('mbeltzner16', 'Marcela', 'Gray heron');
insert into Team (TeamName, TrainerName, PokemonName) values ('cwomersley17', 'Charlie', 'Cape white-eye');
insert into Team (TeamName, TrainerName, PokemonName) values ('aduplan18', 'Adolphe', 'White-necked stork');
insert into Team (TeamName, TrainerName, PokemonName) values ('daliberti19', 'Derron', 'Leadbeateri''s ground hornbill');
insert into Team (TeamName, TrainerName, PokemonName) values ('gturrell1a', 'Gabriellia', 'Snake, eastern indigo');
insert into Team (TeamName, TrainerName, PokemonName) values ('rsmorthit1b', 'Rollo', 'Gull, southern black-backed');
insert into Team (TeamName, TrainerName, PokemonName) values ('radamo1c', 'Reid', 'Swallow (unidentified)');
insert into Team (TeamName, TrainerName, PokemonName) values ('blearoyde1d', 'Bernadina', 'Pelican, brown');
insert into Team (TeamName, TrainerName, PokemonName) values ('mblackmoor1e', 'Madlen', 'European beaver');
insert into Team (TeamName, TrainerName, PokemonName) values ('aklaves1f', 'Annadiane', 'North American river otter');
insert into Team (TeamName, TrainerName, PokemonName) values ('ttoulmin1g', 'Tom', 'Macaw, red and blue');
insert into Team (TeamName, TrainerName, PokemonName) values ('afellowes1h', 'Ainsley', 'Tasmanian devil');
insert into Team (TeamName, TrainerName, PokemonName) values ('avittle1i', 'Aaren', 'Macaque, japanese');
insert into Team (TeamName, TrainerName, PokemonName) values ('ffeatherby1j', 'Frants', 'Sea birds (unidentified)');
insert into Team (TeamName, TrainerName, PokemonName) values ('psteger1k', 'Petunia', 'Eastern fox squirrel');
insert into Team (TeamName, TrainerName, PokemonName) values ('rstobo1l', 'Riki', 'Lapwing, southern');
insert into Team (TeamName, TrainerName, PokemonName) values ('ctebbut1m', 'Chad', 'Canadian tiger swallowtail butterfly');
insert into Team (TeamName, TrainerName, PokemonName) values ('cshadbolt1n', 'Cory', 'Seal, southern elephant');
insert into Team (TeamName, TrainerName, PokemonName) values ('lhedgeley1o', 'Lavinia', 'American badger');
insert into Team (TeamName, TrainerName, PokemonName) values ('cends1p', 'Cristin', 'Violet-eared waxbill');
insert into Team (TeamName, TrainerName, PokemonName) values ('ddarco1q', 'Donnajean', 'Red kangaroo');
insert into Team (TeamName, TrainerName, PokemonName) values ('broebottom1r', 'Brose', 'Duck, white-faced whistling');
insert into Team (TeamName, TrainerName, PokemonName) values ('fchapier1s', 'Fabian', 'Kingfisher, white-throated');
insert into Team (TeamName, TrainerName, PokemonName) values ('lpygott1t', 'Lucila', 'Catfish, blue');
insert into Team (TeamName, TrainerName, PokemonName) values ('dredemile1u', 'Desiree', 'Hanuman langur');
insert into Team (TeamName, TrainerName, PokemonName) values ('tschuelcke1v', 'Thorvald', 'Elephant, asian');
insert into Team (TeamName, TrainerName, PokemonName) values ('lpoundford1w', 'Lonny', 'Otter, oriental short-clawed');
insert into Team (TeamName, TrainerName, PokemonName) values ('gburtwell1x', 'Grayce', 'Hippopotamus');
insert into Team (TeamName, TrainerName, PokemonName) values ('polufsen1y', 'Pennie', 'Barbet, black-collared');
insert into Team (TeamName, TrainerName, PokemonName) values ('zjancso1z', 'Zelig', 'Painted stork');
insert into Team (TeamName, TrainerName, PokemonName) values ('rdoumerque20', 'Rani', 'Turkey, wild');
insert into Team (TeamName, TrainerName, PokemonName) values ('mcorrison21', 'Marigold', 'Woodpecker, downy');
insert into Team (TeamName, TrainerName, PokemonName) values ('mdicte22', 'Maggy', 'Common ringtail');
insert into Team (TeamName, TrainerName, PokemonName) values ('tstienton23', 'Teriann', 'Yellow-crowned night heron');
insert into Team (TeamName, TrainerName, PokemonName) values ('acruwys24', 'Ashley', 'Emerald-spotted wood dove');
insert into Team (TeamName, TrainerName, PokemonName) values ('ahuish25', 'Andree', 'Rhesus monkey');
insert into Team (TeamName, TrainerName, PokemonName) values ('lmaynell26', 'Lyndel', 'Vervet monkey');
insert into Team (TeamName, TrainerName, PokemonName) values ('hbrowne27', 'Heddi', 'Alpaca');
insert into Team (TeamName, TrainerName, PokemonName) values ('whollows28', 'Waldo', 'Buffalo, asian water');
insert into Team (TeamName, TrainerName, PokemonName) values ('obroadfoot29', 'Obadiah', 'Asian false vampire bat');
insert into Team (TeamName, TrainerName, PokemonName) values ('hellerman2a', 'Hannah', 'Black-collared barbet');
insert into Team (TeamName, TrainerName, PokemonName) values ('awillmett2b', 'Alyson', 'Rhea, common');
insert into Team (TeamName, TrainerName, PokemonName) values ('vbozward2c', 'Vania', 'Australian brush turkey');
insert into Team (TeamName, TrainerName, PokemonName) values ('clabbett2d', 'Cleveland', 'Bateleur eagle');
insert into Team (TeamName, TrainerName, PokemonName) values ('mchevins2e', 'Mickie', 'Golden brush-tailed possum');
insert into Team (TeamName, TrainerName, PokemonName) values ('lgorgler2f', 'Loise', 'Lapwing, southern');
insert into Team (TeamName, TrainerName, PokemonName) values ('htrousdale2g', 'Heddi', 'Crimson-breasted shrike');
insert into Team (TeamName, TrainerName, PokemonName) values ('dficken2h', 'Danny', 'Black curlew');
insert into Team (TeamName, TrainerName, PokemonName) values ('lfromant2i', 'Ludovico', 'Squirrel, red');
insert into Team (TeamName, TrainerName, PokemonName) values ('cryburn2j', 'Corbin', 'Red phalarope');
insert into Team (TeamName, TrainerName, PokemonName) values ('pscarsbrick2k', 'Pate', 'Coatimundi, ring-tailed');
insert into Team (TeamName, TrainerName, PokemonName) values ('aambrogioni2l', 'Addison', 'Marine iguana');
insert into Team (TeamName, TrainerName, PokemonName) values ('vfew2m', 'Virgil', 'European spoonbill');
insert into Team (TeamName, TrainerName, PokemonName) values ('bbeardshaw2n', 'Barnabas', 'Monkey, vervet');
insert into Team (TeamName, TrainerName, PokemonName) values ('esleeny2o', 'Elsinore', 'Asian openbill');
insert into Team (TeamName, TrainerName, PokemonName) values ('vgrushin2p', 'Vasilis', 'Meerkat, red');
insert into Team (TeamName, TrainerName, PokemonName) values ('osime2q', 'Olin', 'Eagle, pallas''s fish');
insert into Team (TeamName, TrainerName, PokemonName) values ('jstocken2r', 'Jesus', 'Cobra, egyptian');
